// Define document types and their default prompts
export const REQUIRED_DOCUMENT_TYPES = [
  "HRIS Reports",
  "Business Strategy Documents",
  "Financial Documents",
  "Technology Roadmaps",
  "Pain Points"
] as const;

// Type for document types
export type DocumentType = typeof REQUIRED_DOCUMENT_TYPES[number];

// Create default summarization prompts for each document type
export const DEFAULT_PROMPTS: Record<DocumentType, string> = {
  "HRIS Reports": "**HRIS Report Analysis - Structured Data Extraction & Insight Generation**\n\n---\n\n**Instruction:**  \nAct as an **HR Data Analyst** specialized in **HRIS (Human Resource Information System) reporting**.  \nYour task is to **analyze the provided HRIS report**, extract the **requested information only**, and present it in a **precise, structured format** using tables where applicable.  \nDo **not** make assumptions or provide interpretation beyond the data unless explicitly requested in Part 2.\n\n---\n\n### Part 1: Structured Data Extraction\n\nExtract and organize the following information:\n\n---\n\n#### 1. Organization Overview  \n- **Total number of employees** in the organization  \n\n---\n\n#### 2. Department Analysis  \nCreate a table with the following columns:  \n- **Department Name**  \n- **Employee Count**  \n- **% of Total Workforce**\n\nInstructions:  \n- List all departments  \n- Provide the total count of employees per department  \n- Calculate and include each department's percentage of the total workforce  \n\n---\n\n#### 3. Employee Classification  \nCreate a table with the following columns:  \n- **Employee Type** (e.g., Full-time, Part-time, Contract, Intern)  \n- **Count**  \n- **% of Total Workforce**\n\nThen, for each employee type, summarize their **department distribution** using bullet points or a nested table format if helpful.\n\n---\n\n#### 4. Leadership Structure  \nCreate a table with the following columns:  \n- **Name**  \n- **Title**  \n- **Department Oversight**\n\nInstructions:  \n- List all **C-suite executives**  \n- Provide their exact job titles  \n- Indicate which department(s) each executive oversees  \n\n---\n\n### Part 2: Automatic Insight Generation  \n\nBased strictly on the extracted data, generate **objective, concise insights** under each relevant section.\n\n#### Insight Output Guidelines:\n- Use **bullet points** for all insights  \n- Be **data-driven** – avoid unsupported assumptions  \n- Use **comparative language** (e.g., highest, lowest, majority) where appropriate  \n- Highlight **outliers or unusual patterns**  \n- Focus on **risks, opportunities, structural trends**, and **workforce observations**\n\n---\n\n#### Example Insight Output Format:  \n- *Department A has the highest headcount, representing 35% of the workforce — indicating operational concentration.*  \n- *Contract employees make up 25% of total staff, predominantly in IT and Operations — suggesting flexibility but potential continuity risks.*  \n- *The Marketing Department has only 4% of total staff — possible underinvestment.*  \n- *There is no C-suite leader directly overseeing HR — a potential leadership gap.*\n\n---\n\n**Final Notes:**  \n- Use **tables wherever possible** for structured data  \n- Use **bullet points** for insights and qualitative findings  \n- **Do not provide narrative summaries** unless explicitly asked  \n- Provide **totals and percentages** for all tabulated data for clarity",
  "Business Strategy Documents": "**Strategic Document Extraction - Values, Priorities, Goals & KPI Logic**\n\n---\n\n**Instruction:**  \nAct as a **strategic analyst**.  \nYour task is to extract and summarise key information from the provided **strategy document**.  \nPresent your findings in a **structured, labeled format** as outlined below. Stick closely to the language and logic in the source document and avoid introducing interpretations beyond what is stated unless specifically asked (e.g., in KPI suggestions).\n\n---\n\n### Output Structure:\n\n---\n\n### 1. Company Values  \n- List the **stated company values** exactly as presented.  \n- Summarise in **one sentence** what these values imply for **strategic execution**.\n\n---\n\n### 2. Mission & Long-Term Aspiration  \n- Extract the **mission statement** or **long-term aspiration** verbatim.  \n- Provide a **1–2 sentence summary** of the **strategic intent** based on this.\n\n---\n\n### 3. Strategic Priorities  \nList each **strategic priority** separately.  \nFor each, provide the following:\n\n- **Why it matters** (based on the document's language)  \n- **Measurable goals** linked to the priority  \n- **Key initiatives** planned to achieve the goals  \n\nUse bullet points or a brief paragraph format for clarity.\n\n---\n\n### 4. Consolidated List of Goals  \n- Provide a **bulleted list** of all **measurable goals** mentioned  \n- **Group them by strategic priority**\n\n---\n\n### 5. Consolidated List of Key Initiatives  \n- Provide a **bulleted list** of all **strategic initiatives** referenced  \n- **Group them by strategic priority**\n\n---\n\n### 6. Strategic Design Logic  \n- Summarise the **core strategic thinking** or **drivers** underlying the overall strategy (e.g., growth through innovation, digital leadership, cost efficiency via automation, market share through partnerships)  \n- Keep the summary **focused and concise** (1–2 paragraphs or a bulleted list)\n\n---\n\n### 7. Suggested KPI Framework  \n- Extract any **KPIs** mentioned in the document  \n- Where KPIs are **not explicitly stated**, **infer logical KPIs** that align with each strategic priority and its goals  \n- Present KPI suggestions in a **table format** or as grouped bullet points  \n- Where relevant, distinguish between **leading** and **lagging** indicators\n\n---\n\n**Formatting Guidelines:**  \n- Use **clear labels** for each section  \n- Use **bullet points and tables** where appropriate for readability  \n- Remain **faithful to the document's terminology**  \n- Do not insert commentary or assumptions unless required for **KPI inference**",
  "Financial Documents": "Summarize major expense categories, cost centers, budget allocations, and spending patterns. Highlight significant financial insights and trends.",
  "Technology Roadmaps": "**Extract Technology Strategy Insights for Process Maturity Assessment & Improvement Opportunities**\n\n---\n\n**Instruction:**  \nAct as a **senior enterprise process consultant** and **digital transformation strategist**.  \nYour objective is to **analyze a technology strategy document** to support a **process maturity assessment** and surface **opportunities for improvement**. Focus on aligning technology initiatives with business strategy, process outcomes, and maturity enhancement.\n\n---\n\n**Your Response Must Be Structured Using the Following Headings:**\n\n---\n\n### 1. Technology Vision & Strategic Alignment\n- Extract the stated **technology vision or strategic objective** (verbatim, if possible).  \n- Summarise how the **technology strategy supports the overall business strategy**.  \n- Highlight statements that **link technology to business value**, growth, or **competitive advantage**.  \n\n---\n\n### 2. Technology Priorities & Focus Areas  \nList each strategic **technology priority or focus area** (e.g., cloud, data, automation):  \nFor each:\n- **Why it matters** to the business  \n- **Stated goals or outcomes**  \n- **Impact on current or future-state processes**\n\n---\n\n### 3. Core Technology Initiatives  \nList the major **technology programs, platforms, or initiatives**:  \nFor each:\n- **Strategic intent**  \n- **Expected impact** on process maturity (e.g., automation, integration, standardisation)  \n- Relevant **tools, technologies, or platforms**\n\n---\n\n### 4. Process Maturity Insights (Explicit or Implied)  \n- Identify any **process domains** mentioned (e.g., HR, finance, supply chain)  \n- Extract descriptions of **current-state maturity** (e.g., manual, fragmented, siloed)  \n- Summarise **gaps or inefficiencies** observed or implied  \n\n---\n\n### 5. Opportunities for Process Improvement  \nBased on the above, infer and list **opportunities for process improvement**:  \nFor each:\n- **Target process area**  \n- **Desired future-state maturity**  \n- **Enabling technology or strategic initiative**\n\n---\n\n### 6. Strategic Design Principles & Enablers  \n- List any **design principles** or **architectural philosophies** (e.g., platform-first, automation-first)  \n- Note any **enterprise enablers** mentioned (e.g., data strategy, governance, change management)\n\n---\n\n### 7. Suggested Maturity Metrics or KPIs  \n- Extract any **stated KPIs or performance metrics**  \n- Where none are found, **infer relevant KPIs** that would measure success in improving maturity  \n- Suggest **leading and lagging indicators** for each priority area  \n\n---\n\n**Additional Guidance:**  \n- Use **concise bullet points** or short summaries  \n- Indicate **\"Not Found\"** where no relevant content exists  \n- Focus on **process implications and actionable insights**, not just descriptions of technology",
  "Pain Points": "Identify key challenges, obstacles, and pain points mentioned across the organization. Focus on operational bottlenecks, process inefficiencies, and areas of improvement."
};

// Add document agent roles for each document type
export const DOCUMENT_AGENT_ROLES: Record<DocumentType, string> = {
  "HRIS Reports": "You are an HR data analyst specialized in workforce analytics. Extract structured organizational data, identify department distributions, analyze employee classifications, map leadership structures, and generate data-driven workforce insights.",
  "Business Strategy Documents": "You are a strategic document analyst who extracts company values, mission statements, strategic priorities, measurable goals, key initiatives, and develops KPI frameworks while preserving the source document's logic and terminology.",
  "Financial Documents": "You are a financial data analyst who identifies expense categories, cost centers, budget allocations, and spending patterns to highlight significant financial trends and resource optimization opportunities.",
  "Technology Roadmaps": "You are a technology strategy consultant who assesses process maturity by analyzing technology vision, priorities, initiatives, and architectural principles to identify improvement opportunities and alignment with business objectives.",
  "Pain Points": "You are a process improvement specialist who identifies operational bottlenecks, organizational challenges, and efficiency gaps by analyzing documented pain points to highlight priority areas for intervention."
};

// Add document descriptions
export const DOCUMENT_DESCRIPTIONS: Record<DocumentType, string> = {
  "HRIS Reports": "Upload the company's Human Resource Information System reports.",
  "Business Strategy Documents": "Upload the company's strategic plans and initiatives.",
  "Financial Documents": "Upload General Ledger, Chart of Accounts, P&L Statement and Balance Sheet for your organisation (technology only).",
  "Technology Roadmaps": "Upload the company's technology implementation plans and roadmaps.",
  "Pain Points": "Upload documents highlighting any existing key challenges and pain points within the organization."
}; 